<?xml version="1.0" encoding="UTF-8"?>
<testrun name="TestUserDao.testListUserRoles" project="cms-core" tests="1" started="0" failures="0" errors="1" ignored="0">
  <testcase name="testListUserRoles" classname="org.leejianhao.cms.dao.TestUserDao" incomplete="true"/>
  <testsuite name="Unrooted Tests">
    <testcase name="org.leejianhao.cms.dao.TestUserDao" classname="org.leejianhao.cms.dao.TestUserDao">
      <error>com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'fz_cms'&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)&#13;
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)&#13;
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:408)&#13;
	at com.mysql.jdbc.Util.getInstance(Util.java:383)&#13;
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1062)&#13;
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4208)&#13;
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4140)&#13;
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:925)&#13;
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1747)&#13;
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1287)&#13;
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2494)&#13;
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2527)&#13;
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2309)&#13;
	at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:834)&#13;
	at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:46)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)&#13;
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)&#13;
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:408)&#13;
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:419)&#13;
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:344)&#13;
	at java.sql.DriverManager.getConnection(DriverManager.java:582)&#13;
	at java.sql.DriverManager.getConnection(DriverManager.java:185)&#13;
	at org.leejianhao.basic.test.util.DbUtil.getConnection(DbUtil.java:12)&#13;
	at org.leejianhao.basic.test.util.AbstractDbUnitTestCase.init(AbstractDbUnitTestCase.java:32)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)&#13;
	at java.lang.reflect.Method.invoke(Method.java:597)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)&#13;
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:176)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
